theme = "dynamic"
window_size = [
    1920.0,
    1080.0,
]
enable_backdrop = false
hyprland_auto_blur = false
enable_transparency = true

[[search_providers]]
name = "Google"
trigger = "!g"
url = "https://www.google.com/search?q={query}"
icon = "magnifying-glass"

[[search_providers]]
name = "DuckDuckGo"
trigger = "!d"
url = "https://duckduckgo.com/?q={query}"
icon = "globe"

[[search_providers]]
name = "Wikipedia"
trigger = "!wiki"
url = "https://en.wikipedia.org/wiki/Special:Search?search={query}"
icon = "book-open"

[[search_providers]]
name = "YouTube"
trigger = "!yt"
url = "https://www.youtube.com/results?search_query={query}"
icon = "youtube-logo"

[fuzzy_match]
exact_match_bonus = 100000
prefix_match_bonus = 50000
word_prefix_bonus = 25000
contiguity_bonus = 10000
description_penalty = 0.3
action_score_multiplier = 0.8
submenu_score_multiplier = 0.9
show_best_match = true
