[config]

[config.wallpaper]
set = true
command = "awww img --transition-type center --transition-step 90 --transition-fps 60 {{ image }}"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/current.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.hyprland]
input_path = '/usr/share/kwimy-hypr/colors/matugen.conf'
output_path = '~/.local/share/kwimy/hypr/colors.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/kwimy/Matugen.colors'

[templates.swaync]
input_path = "./colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.zlaunch]
input_path = '~/.config/matugen/templates/zlaunch.toml'
output_path = '~/.config/zlaunch/themes/dynamic.toml'
post_hook = 'zlaunch reload'
