name = 'dynamic'

window_background = "{{colors.background.default.hex}}ee"

window_border = "{{colors.secondary.default.hex}}33"
window_border_radius = 12.0

# Input
input_background = "{{colors.background.default.hex}}ee"
input_text = "{{colors.tertiary.default.hex}}"
input_placeholder = "#565f89"
input_caret = "#7aa2f7"

# Items
item_background = "{{colors.background.default.hex}}"
item_background_hover = "#24283b"
item_background_selected = "{{colors.secondary.default.hex}}33"
item_text = "#c0caf5"
item_text_secondary = "#565f89"

# Icons
icon_background = "#ff0000"
icon_color = "#7aa2f7"

# Sections
section_text = "#e0af68"
section_background = "#1a1b26"

# Scrollbar
scrollbar_track = "#16161e"
scrollbar_thumb = "#292e42"
scrollbar_thumb_hover = "#3b4261"

[calculator]
result_text = "#9ece6a"
error_color = "#f7768e"

[emoji]
columns = 8
cell_size = 72.0

[ai]
user_bubble_background = "#7aa2f733"
assistant_bubble_background = "#24283b"

[markdown]
code_background = "#16161e"
code_text = "#e0af68"
link_color = "#7aa2f7"
